# OAuth 정보 (Secret)

# Facebook
spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-name: facebook
            client-id: "{FACEBOOK_CLIENT_ID}"
            client-secret: "{FACEBOOK_CLIENT_SECRET}"
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/dialog/oauth
            tokenUri: https://graph.facebook.com/oauth/access_token
            userInfoUri: https://graph.facebook.com/me?fields=id,name,email