spring:
  profiles:
    # TODO: Oauth2 profile 은 수정해서 추가하기
    include: secret, connection # oauth2

# Secret values for JWT
app:
  auth:
    secret-token: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    token-expiration-milli-sec: 864000000 # 하루
  oauth2:
    authorized-redirect-uris:
      - http://localhost:8080/auth/token


