spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  profiles:
    include: secret

# OAuth 정보 (Secret)
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: "{FACEBOOK_CLIENT_ID}"
            client-secret: "{FACEBOOK_CLIENT_SECRET}"
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/dialog/oauth
            tokenUri: https://graph.facebook.com/oauth/access_token
            userInfoUri: https://graph.facebook.com/me?fields=id,name,email


# Secret values for JWT
app:
  auth:
    secret-token: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    token-expiration-milli-sec: 864000000 # 하루
  oauth2:
    authorized-redirect-uris:
      - http://localhost:8080/oauth2/redirect


